import Head from 'next/head'
import routes from 'db/routes'
import Button from 'components/button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {routes.map((item, index) => (
          <li key={index}>
            <Button route={item.rota} name={item.nome}></Button>
          </li>
        ))}
      </ul>
    </>
  )
}
